### ISSUE TITLE
RuntimeError:element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by mingzhu-wu** [mrqa/MRQA-Shared-Task-2019#16]
Hi,
I got an error while training the MTBert baseline without SQuAD dataset, all the rest settings are the same with the example command except for the number of t_total. 

The error is as follows:
File "/home/ukp/mwu/MRQA-Shared-Task-2019/baseline/venv-3.6/lib/python3.6/site-packages/allennlp/commands/train.py", line 243, in train_model
metrics = trainer.train()
File "/home/ukp/mwu/MRQA-Shared-Task-2019/baseline/venv-3.6/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
train_metrics = self._train_epoch(epoch)
File "/home/ukp/mwu/MRQA-Shared-Task-2019/baseline/venv-3.6/lib/python3.6/site-packages/allennlp/training/trainer.py", line 327, in _train_epoch
loss.backward()
File "/home/ukp/mwu/MRQA-Shared-Task-2019/baseline/venv-3.6/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/ukp/mwu/MRQA-Shared-Task-2019/baseline/venv-3.6/lib/python3.6/site-packages/torch/autograd/init.py", line 93, in backward
allow_unreachable=True) # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

The same error happens when I tried to add additional training examples. 
I would be really appreciated to know the reason of this error and how to fix it.
Thanks in advance.

**Comment by alontalmor** [comment]
Hi xfwmz, you referred to ZHO9504 problem. Do you also experience this only on 2 GPUs? what is your running command? which version of AllenNLP do you use? (also there was a code update in the last few weeks to the baseline model, be sure you are using the latest code)

**Comment by ZHO9504** [comment]
I got this error too..

**Comment by alontalmor** [comment]
can you please send me the allennlp command you used here? thanks

**Comment by xfwmz** [comment]
> Hi xfwmz, you referred to ZHO9504 problem. Do you also experience this only on 2 GPUs? what is your running command? which version of AllenNLP do you use? (also there was a code update in the last few weeks to the baseline model, be sure you are using the latest code)

Hi alontalmor, thank you for your reply. I had this error when I use only 1 GPU, and the Allennlp version is 0.8.4. 
My running command is as following: 
python -m allennlp.run train https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s /ukp-storage-1/mwu/MRQA-Shared-Task-2019/Models/Train-qa -o "{'dataset_reader': {'sample_size': 75000}, 'validation_dataset_reader': {'sample_size': 1000}, 'train_data_path': '/ukp-storage-1/mwu/MRQA-Shared-Task-2019/data_train/augmented/qa_train.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/NaturalQuestionsShort.jsonl.gz', 'trainer': {'cuda_device': 0, 'num_epochs': '2', 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': '25000'}}}" --include-package mrqa_allennlp

The training data qa_train.jsonl.gz is some artificial data I generated according to the MRQA format, I evaluated it with trained MTBert base, it worked well. So I assume the data format is okay. However, when I used it for training, either single dataset training or multi-task training, I always get this error.
Maybe it is the problem with my data, but there should have been some remainder or warning about that. 

And my colleague also reports having this error when using the provided data and setting for training MTBert Base without SQuAD,  the command may look like this:
python -m allennlp.run train s3://multiqa/config/MRQA_BERTbase.json -s ../Models/MultiTrain -o "{'dataset_reader': {'sample_size': 75000}, 'validation_dataset_reader': {'sample_size': 1000}, 'train_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/train/NewsQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/HotpotQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/SearchQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/TriviaQA-web.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/NaturalQuestionsShort.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/NewsQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/HotpotQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SearchQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/TriviaQA-web.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/NaturalQuestionsShort.jsonl.gz', 'trainer': {'cuda_device': 0, 'num_epochs': '2', 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': '120000'}}}" --include-package mrqa_allennlp

One example of the the artificial data looks like this:
{"id": "", "context": "On April 11 the former longtime ally of Hadi in Zinibar and Khanfir, Abdul Latif Al-Sayed, resigned from his Hizam post, siting organizational failure to fight expanding AQAP forces in Abyan. Afterwards, he took command of the UAE-loyal backed Rapid Deployment Force in Abyan.", "context_tokens": [["On", 0], ["April", 3], ["11", 9], ["the", 12], ["former", 16], ["longtime", 23], ["ally", 32], ["of", 37], ["Hadi", 40], ["in", 45], ["Zinibar", 48], ["and", 56], ["Khanfir", 60], [",", 67], ["Abdul", 69], ["Latif", 75], ["Al", 81], ["-", 83], ["Sayed", 84], [",", 89], ["resigned", 91], ["from", 100], ["his", 105], ["Hizam", 109], ["post", 115], [",", 119], ["siting", 121], ["organizational", 128], ["failure", 143], ["to", 151], ["fight", 154], ["expanding", 160], ["AQAP", 170], ["forces", 175], ["in", 182], ["Abyan", 185], [".", 190], ["Afterwards", 192], [",", 202], ["he", 204], ["took", 207], ["command", 212], ["of", 220], ["the", 223], ["UAE", 227], ["-", 230], ["loyal", 231], ["backed", 237], ["Rapid", 244], ["Deployment", 250], ["Force", 261], ["in", 267], ["Abyan", 270], [".", 275]], "qas": [{"qid": "4e2558702841027e615c089f1acb395d5451e2fc", "question": "Where are the AQAP forces ?", "question_tokens": [["Where", 0], ["are", 6], ["the", 10], ["AQAP", 14], ["forces", 19], ["?", 26]], "detected_answers": [{"text": "Abyan", "char_spans": [[185, 189]], "token_spans": [[35, 35]]}], "answers": ["Abyan"]}, {"qid": "4e2558702841027e615c089f1acb395d5451e2fc", "question": "Where are the AQAP forces ?", "question_tokens": [["Where", 0], ["are", 6], ["the", 10], ["AQAP", 14], ["forces", 19], ["?", 26]], "detected_answers": [{"text": "Abyan", "char_spans": [[185, 189]], "token_spans": [[35, 35]]}], "answers": ["Abyan"]}]}

**Comment by mingzhu-wu** [comment]
> can you please send me the allennlp command you used here? thanks

Hi alontalmor, I reproduced this error with the following command: 
python -m allennlp.run train https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s MRQA-Shared-Task-2019/Models/MultiTrain -o "{'dataset_reader': {'sample_size': 75000}, 'validation_dataset_reader': {'sample_size': 1000}, 'train_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/train/NewsQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/HotpotQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/SearchQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/TriviaQA-web.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/train/NaturalQuestionsShort.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SQuAD.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/NewsQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/HotpotQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SearchQA.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/TriviaQA-web.jsonl.gz,https://mrqa.s3.us-east-2.amazonaws.com/data/dev/NaturalQuestionsShort.jsonl.gz', 'trainer': {'cuda_device': 0, 'num_epochs': '2', 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': '120000'}}}" --include-package mrqa_allennlp

I was running this command on 1 GPU, using allennlp version 0.8.4, this error appeared after 8 hours of training when the EM score reaches 54, as shown in the following:
EM: 54.6440, f1: 65.0914, qas_used_fraction: 1.0000, loss: 4.2103 ||: : 59878it [7:06:57,  2.50it/s]
EM: 54.6462, f1: 65.0929, qas_used_fraction: 1.0000, loss: 4.2101 ||: : 59906it [7:07:08,  2.54it/s]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/run.py", line 21, in <module>
    run()
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/commands/train.py", line 116, in train_model_from_args
    args.cache_prefix)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/commands/train.py", line 160, in train_model_from_file
    cache_directory, cache_prefix)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/commands/train.py", line 243, in train_model
    metrics = trainer.train()
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/allennlp/training/trainer.py", line 327, in _train_epoch
    loss.backward()
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/ukp-storage-1/mwu/venv-mrqa/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by mingzhu-wu** [comment]
I found the bug that results in this RuntimeError, it happens when a batch contains only one training example, then the expression "len(np.argwhere(span_start.squeeze().cpu() >= 0)) > 0" in BERT_QA.py line 91 would be false even if the gold answer is given. In this case, the output loss will be zero and this error happens.

I fixed this bug by modifying the expression from "if span_start is not None and len(np.argwhere(span_start.squeeze().cpu() >= 0)) > 0:" to  "if span_start is not None and len(np.argwhere(span_start.squeeze(-1).squeeze(-1).cpu() >= 0)) > 0:", now it works fine.
